# These are supported funding model platforms

github: [juanro49] [clefebvre] [gm10] [JosephMcc] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g.,
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.me/juanro49 # Replace with a single custom sponsorship URL
custom: https://www.linuxmint.com/donors.php
