#!/bin/bash
intltool-extract --type=gettext/glade usr/share/distroupdate/history.ui
intltool-extract --type=gettext/glade usr/share/distroupdate/information.ui
intltool-extract --type=gettext/glade usr/share/distroupdate/kernels.ui
intltool-extract --type=gettext/glade usr/share/distroupdate/main.ui
intltool-extract --type=gettext/glade usr/share/distroupdate/preferences.ui
intltool-extract --type=gettext/glade usr/share/distroupdate/shortcuts.ui
xml2po -o mintupdate.pot -m mallard usr/share/help/C/mintupdate/*.page
xgettext --language=Python --keyword=_ --keyword=N_ --output=mintupdate.pot --join-existing usr/lib/distroUpdate/*.py generate_desktop_files usr/bin/distroupdate-cli usr/bin/mint-release-upgrade usr/bin/mint-release-upgrade-root usr/lib/distroUpdate/aliases usr/share/distroupdate/*.ui.h
rm -f usr/share/distroupdate/*.ui.h
